<?php


$errors = [
    1000 => 'Xml Inválido',
    1001 => 'Lote Inválido',
    1002 => 'Sem Tag <ID_Token>',
    1003 => 'Tag <ID_Token> nula ou em branco',
    1004 => 'Tag <ID_Token> inválida',
    1005 => 'Sem Tag <NR_Nota_Fiscal>',
    1006 => 'Tag <NR_Nota_Fiscal> nula ou em branco',
    1007 => 'Tag <NR_Nota_Fiscal> maior que 9 dígitos',
    1008 => 'Sem Tag <DT_Emissao>',
    1009 => 'Tag <DT_Emissao> nula ou em branco',
    1010 => 'Tag <DT_Emissao> não é uma data válida',
    1011 => 'Tag <DT_Emissao> maior que a data atual',
    1012 => 'Sem Tag <OP_Tipo_Lote>',
    1013 => 'Tag <OP_Tipo_Lote> nula ou em branco',
    1014 => 'Tag <OP_Tipo_Lote> maior que 3 ou menor que 1',
    1015 => 'Sem Tag <NR_Cnpj_Faccionista>',
    1016 => 'Tag <NR_Cnpj_Faccionista> nula ou em branco',
    1017 => 'Tag <NR_Cnpj_Faccionista> maior que 18 dígitos',
    1018 => 'Tag <NR_Cnpj_Faccionista> não condiz com a Tag <OP_Tipo_Lote>',
    1019 => 'Tag <NR_Cnpj_Faccionista> em conjunto com <NR_Nota_Fiscal> já cadastrados.',
    1020 => 'Romaneio inválido',
    1021 => 'Sem Tag <NR_Romaneio>',
    1022 => 'Tag <NR_Romaneio> nula ou em branco',
    1023 => 'Tag <NR_Romaneio> maior que 7 dígitos',
    1024 => 'Tag <NR_Romaneio> já existente nesse Lote',
    1025 => 'Sem Tag <DC_Artigo>',
    1026 => 'Tag <DC_Artigo> nula ou em branco',
    1027 => 'Tag <DC_Artigo> maior que 16 dígitos',
    1028 => 'Tag <DC_Artigo> não pertence a esse usuário',
    1029 => 'Sem Tag <DC_Cor>',
    1030 => 'Tag <DC_Cor> nula ou em branco',
    1031 => 'Tag <DC_Cor> maior que 57 dígitos',
    1032 => 'Tag <DC_Cor> não pertence a esse usuário',
    1033 => 'Sem Tag <OP_Tipo>',
    1034 => 'Tag <OP_Tipo> nula ou em branco',
    1035 => 'Tag <OP_Tipo> maior que 3 ou menor que 0',
    1036 => 'Sem Tag <NR_Cod_Produto>',
    1037 => 'Tag <NR_Cod_Produto> nula ou em branco',
    1038 => 'Tag <NR_Cod_produto> maior que 25 dígitos',
    1039 => 'Sem Tag <NR_Largura>',
    1040 => 'Tag <NR_Largura> nula ou em branco',
    1041 => 'Tag <NR_Largura> maior que 3 ou menor que 0.4',
    1042 => 'Tag <NR_Largura> não é um número',
    1043 => 'Sem Tag <NR_Gramatura>',
    1044 => 'Tag <NR_Gramatura> nula ou em branco',
    1045 => 'Tag <NR_Gramatura> maior que 160 ou menor que 0',
    1046 => 'Sem Tag <DC_Obs>',
    1047 => 'Tag <DC_Obs> maior que 50 dígitos',
    1048 => 'Peça inválida',
    1049 => 'Sem Tag <NR_Peca>',
    1050 => 'Tag <NR_Peca> nula ou em branco',
    1051 => 'Tag <NR_Peca> maior que 10 dígitos',
    1052 => 'Tag <NR_Peca> já existente nesse Lote',
    1053 => 'Sem Tag <NR_Peso>',
    1054 => 'Tag <NR_Peso> nula ou em branco',
    1055 => 'Tag <NR_Peso> maior que 160 ou menor que 0',
    1056 => 'Tag <NR_Peso> não é um número válido',
    1057 => 'Sem Tag <NR_Comprimento>',
    1058 => 'Tag <NR_Comprimento> nula ou em branco',
    1059 => 'Tag <NR_Comprimento> maior que 1200 ou menor que 0',
    1060 => 'Tag <NR_Comprimento> não é um número válido',
    1061 => 'Sem Tag <DC_Maquina>',
    1062 => 'Tag <DC_Maquina> maior que 10 dígitos',
    1063 => 'Sem Tag <DC_Maquina_Lote>',
    1064 => 'Tag <DC_Maquina_Lote> maior que 8 dígitos',
    1065 => 'Sem Conexão com o Banco de Dados',
    1066 => 'Erro desconhecido',
    1067 => 'Caminho não encontrado',
    1068 => 'Não foi possível salvar o arquivo',
];

foreach($errors as $key => $value) {
    $errors[$key] = htmlentities($value);
}

$json = json_encode($errors, JSON_PRETTY_PRINT);
file_put_contents('../storage/errors.json', $json);